server:
  port: 9099

spring:
  application:
    name: FACILITYSERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/citycare_facility?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 15000
            loggerLevel: full

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: Y2Y4ZTM1YmYtYjYyMC00ZDllLTlhZTMtZDY2ZDU4ZTMxZmE5Cg==
  expiration:
    ms: 1800000

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full

logging:
  level:
    org.citycare.facilityservice: DEBUG
    org.springframework.web: INFO

