server:
  port: 8082

spring:
  application:
    name: PATIENTTREATMENTSERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/citycare_patient_treatment
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: Y2Y4ZTM1YmYtYjYyMC00ZDllLTlhZTMtZDY2ZDU4ZTMxZmE5Cg==
  expiration:
    ms: 1800000

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    org.citycare.patienttreatmentservice: DEBUG
    org.springframework.web: INFO

