package org.citycare.security.jwt;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * Centralized JWT Token Generator for CityCare platform.
 *
 * This component handles ALL token generation across services, ensuring
 * consistent cryptography, format, and expiration policies.
 *
 * Two use cases:
 * 1. User tokens (generated by AuthService after authentication)
 *    - Long-lived (30 min default)
 *    - Contains userId, role, email
 *    - Subject: user's email
 *
 * 2. Service tokens (generated by services for inter-service calls)
 *    - Short-lived (60 sec)
 *    - Contains serviceId, role (e.g., ROLE_ADMIN)
 *    - Subject: service name
 *
 * Usage:
 *   AuthService: jwtTokenGenerator.generateUserToken(user, expirationMs)
 *   NotificationService: jwtTokenGenerator.generateServiceToken("notification-service", 60000)
 */
@Component
public class JwtTokenGenerator {

    @Value("${jwt.secret}")
    private String secretKey;

    /**
     * Generate a user authentication token.
     *
     * Called by AuthService after successful user login/registration.
     * Token includes userId, role, and user email as subject.
     *
     * @param subject User's email (will be extractable via getSubject())
     * @param userId  User's ID
     * @param role    User's role (e.g., "CITIZEN", "DOCTOR", "DISPATCHER")
     * @param expirationMs Token lifetime in milliseconds (typically 1800000 = 30 min)
     * @return Signed JWT token
     */
    public String generateUserToken(String subject, Long userId, String role, long expirationMs) {
        Map<String, Object> claims = new HashMap<>();
        claims.put("userId", userId);
        claims.put("role", role);

        return buildToken(claims, subject, expirationMs);
    }

    /**
     * Generate a user authentication token with custom claims.
     *
     * Called by AuthService when adding extra information to token.
     * Example: department, specialty, facility ID, etc.
     *
     * @param subject User's email (will be extractable via getSubject())
     * @param userId  User's ID
     * @param role    User's role
     * @param additionalClaims Extra claims to include (e.g., department, specialty)
     * @param expirationMs Token lifetime in milliseconds
     * @return Signed JWT token
     */
    public String generateUserToken(String subject, Long userId, String role,
                                   Map<String, Object> additionalClaims, long expirationMs) {
        Map<String, Object> claims = new HashMap<>(additionalClaims);
        claims.put("userId", userId);
        claims.put("role", role);

        return buildToken(claims, subject, expirationMs);
    }

    /**
     * Generate a service-to-service authentication token.
     *
     * Called by services (e.g., NotificationService) to authenticate
     * when making inter-service calls via Feign/OpenFeign.
     *
     * These tokens are typically short-lived (60-120 seconds) and
     * carry a service identifier and elevated privileges (ROLE_ADMIN).
     *
     * @param serviceName Service identifier (e.g., "notification-service", "citizen-service")
     * @param expirationMs Token lifetime in milliseconds (typically 60000 = 60 sec)
     * @return Signed JWT token
     */
    public String generateServiceToken(String serviceName, long expirationMs) {
        Map<String, Object> claims = new HashMap<>();
        claims.put("userId", 0L);  // Service tokens don't represent users
        claims.put("role", "ROLE_ADMIN");  // Services are privileged
        claims.put("serviceId", serviceName);

        return buildToken(claims, serviceName, expirationMs);
    }

    /**
     * Generate a service-to-service token with custom role.
     *
     * For cases where a service needs a different privilege level.
     *
     * @param serviceName Service identifier
     * @param role Role to assign (e.g., "ROLE_ADMIN", "ROLE_SERVICE")
     * @param expirationMs Token lifetime in milliseconds
     * @return Signed JWT token
     */
    public String generateServiceToken(String serviceName, String role, long expirationMs) {
        Map<String, Object> claims = new HashMap<>();
        claims.put("userId", 0L);
        claims.put("role", role);
        claims.put("serviceId", serviceName);

        return buildToken(claims, serviceName, expirationMs);
    }

    /**
     * Core token building logic. Internal method used by all public generators.
     *
     * @param claims Claims to include in token
     * @param subject Token subject (usually email or service name)
     * @param expirationMs Token lifetime in milliseconds
     * @return Signed JWT token
     */
    private String buildToken(Map<String, Object> claims, String subject, long expirationMs) {
        SecretKey key = getSignKey();
        long currentTimeMillis = System.currentTimeMillis();

        return Jwts.builder()
                .header().add("typ", "JWT").and()
                .claims(claims)
                .subject(subject)
                .issuedAt(new Date(currentTimeMillis))
                .expiration(new Date(currentTimeMillis + expirationMs))
                .signWith(key)
                .compact();
    }

    /**
     * Internal method to get the signing key from base64-encoded secret.
     *
     * @return SecretKey for HMAC-SHA signing
     */
    private SecretKey getSignKey() {
        byte[] keyBytes = Decoders.BASE64URL.decode(secretKey);
        return Keys.hmacShaKeyFor(keyBytes);
    }
}

