package org.citycare.facilityservice.servicesImpl;

import lombok.RequiredArgsConstructor;
import org.citycare.facilityservice.client.IamClient;
import org.citycare.facilityservice.dto.request.StaffRequest;
import org.citycare.facilityservice.dto.response.ApiResponse;
import org.citycare.facilityservice.dto.response.StaffResponse;
import org.citycare.facilityservice.dto.response.UserResponse;
import org.citycare.facilityservice.entities.Facility;
import org.citycare.facilityservice.entities.Staff;
import org.citycare.facilityservice.exceptions.ResourceNotFoundException;
import org.citycare.facilityservice.repositories.FacilityRepository;
import org.citycare.facilityservice.repositories.StaffRepository;
import org.citycare.facilityservice.services.StaffService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class StaffServiceImpl implements StaffService {

    private final StaffRepository staffRepository;
    private final FacilityRepository facilityRepository;
    private final IamClient iamClient;

    @Override
    @Transactional
    public StaffResponse createStaff(StaffRequest request) {
        // 1. Verify Facility exists locally
        Facility facility = facilityRepository.findById(request.getFacilityId())
                .orElseThrow(() -> new ResourceNotFoundException("Facility", request.getFacilityId()));

        ApiResponse<UserResponse> iamResponse;

        // Using Java 21 Pattern Matching/Switch
        iamResponse = switch (request.getRole()) {
            case DOCTOR, NURSE -> iamClient.createStaffAccount(request);
            case DISPATCHER -> iamClient.createDispatcherAccount(request);
            case COMPLIANCE_OFFICER -> iamClient.createComplianceAccount(request);
            case HEALTH_OFFICER -> iamClient.createHealthOfficerAccount(request);
            default -> throw new IllegalArgumentException("Unsupported role for staff creation: " + request.getRole());
        };

        // 3. Extract the User data from the wrapper
        UserResponse user = iamResponse.getData();

        // 4. Save to Facility Service DB (Linking the IAM userId)
        Staff staff = Staff.builder()
                .staffId(user.getUserId()) // The ID generated by AuthService its primary key
                .name(request.getName())
                .role(request.getRole())
                .contactInfo(request.getPhone())
                .facility(facility)
                .status(Staff.Status.ACTIVE)
//                .userId(user.getUserId())
                .build();

        Staff savedStaff = staffRepository.save(staff);
        return mapToResponse(savedStaff);
    }

    @Override
    public StaffResponse getStaffById(Long id) {

        Staff staff = staffRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Staff", id));
        return mapToResponse(staff);
    }

    @Override
    public List<StaffResponse> getAllStaff() {
        return staffRepository.findAll().stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional
    public StaffResponse updateStaffStatus(Long id, Staff.Status status) {
        Staff staff = staffRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Staff", id));
        staff.setStatus(status);
        return mapToResponse(staffRepository.save(staff));
    }

    @Override
    public List<StaffResponse> getStaffByFacility(Long facilityId) {
        if (!facilityRepository.existsById(facilityId)) {
            throw new ResourceNotFoundException("Facility", facilityId);
        }
        return staffRepository.findByFacilityFacilityId(facilityId).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    public List<StaffResponse> getStaffByRole(Staff.Role role) {
        return staffRepository.findByRole(role).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional
    public void deleteStaff(Long id) {
        if (!staffRepository.existsById(id)) {
            throw new ResourceNotFoundException("Staff", id);
        }
        staffRepository.deleteById(id);
    }

    // --- Helper for DTO Mapping ---
    private StaffResponse mapToResponse(Staff staff) {
        return StaffResponse.builder()
                .staffId(staff.getStaffId()) // Primary Key
                .userId(staff.getStaffId())  // Shared Identity
                .name(staff.getName())
                .role(staff.getRole())
                .contactInfo(staff.getContactInfo())
                .status(staff.getStatus())
                .facilityId(staff.getFacility().getFacilityId())
//                .userId(staff.getUserId())
                .build();
    }
}