server:
  port: 9090

jwt:
  secret: Y2Y4ZTM1YmYtYjYyMC00ZDllLTlhZTMtZDY2ZDU4ZTMxZmE5Cg==
  expiration:
    ms: 1800000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true
      routes:
        - id: AUTHSERVICE
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**, /admin/**, /users/**
        - id: FACILITYSERVICE
          uri: lb://FACILITYSERVICE
          predicates:
            - Path=/facilities/**, /staff/**
        - id: EMERGENCYSERVICE
          uri: lb://EMERGENCYSERVICE
          predicates:
            - Path=/emergencies/**
        - id: PATIENTTREATMENTSERVICE
          uri: lb://PATIENTTREATMENTSERVICE
          predicates:
            - Path=/patients/**, /treatments/**
        - id: CITIZENSERVICE
          uri: lb://CITIZENSERVICE
          predicates:
            - Path=/api/citizens/**
        - id: NOTIFICATIONSERVICE
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/notifications/**
        - id: COMPLIANCESERVICE
          uri: lb://COMPLIANCESERVICE
          predicates:
            - Path=/compliance/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
